### ISSUE TITLE
Console Errors (Could not pass event EntityDamageByEntityEvent)

### ISSUE THREAD

**Issue by meowsome** [cjburkey01/ClaimChunk#111]
Spigot Version: 1.12
ClaimChunk Version: 0.0.17

These errors (and more) occur in console with latest version of the plugin, seemingly at random when there's somebody online interacting with the plugin in some way (using commands, going in and out of chunks, etc):
https://pastebin.com/RuX66iJr

**Comment by cjburkey01** [comment]
Yeah, I've seen some people complaining about those. They are fixed in the 0.0.18 snapshots because I rewrote the entire event system. Unfortunately, those snapshots are pretty unstable and I haven't had a chance to test them extensively. One of the members on the Discord server updated their server to the latest version and I haven't heard of any issues yet so, if you want, I could provide you one of those versions, but I make no promises to whether they work well or have issues.

**Comment by cjburkey01** [comment]
I'm going to release 0.0.18 soon and this is fixed in that version
