### ISSUE TITLE
Always show owned chunk borders.

### ISSUE THREAD

**Issue by Xd-pro** [cjburkey01/ClaimChunk#165]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A way to show particles for all the chunks you own.

**Describe alternatives you've considered**
Structure-block based CUI.

**Additional context**
No.

**Comment by cjburkey01** [comment]
Unfortunately I believe the structure blocks won't display on client side unless they're in creative mode so we're still stuck with particle effects. There is already a request to add a map into chat (https://github.com/cjburkey01/ClaimChunk/issues/107) which doesn't exactly target your issue, but it would give a way of seeing the overall structure of your claim. In theory, I could also add a second parameter to the `/chunk show` command to allow an optional chunk radius, though heavy particle effects on the server may cause lag through the current system. For modern versions of Spigot, we may use a new particle system that is probably miles more efficient as it doesn't require frequent calls to slow reflection calls. I've created an issue to track that here: https://github.com/cjburkey01/ClaimChunk/issues/169

In the meantime, however, I'll leave this issue open because I reference it there and this remains a unique enough issue to keep.

**Comment by cjburkey01** [comment]
Closing because this is over 3 years old
