### ISSUE TITLE
Wither Boss and Tnt

### ISSUE THREAD

**Issue by Biblilichine** [cjburkey01/ClaimChunk#195]
Hey ^^ 
Would it also be possible to reactivate the / claimchunk tnt command which no longer works in the latest Snapshot 0.0.23 of the plugin and to deactivate the wither boss explosions in the chunks

Thank you ;)

**Comment by cjburkey01** [comment]
Oh looks like it's a special event, let me try to implement it real quick

**Comment by cjburkey01** [comment]
It should have been fixed in this commit: https://github.com/cjburkey01/ClaimChunk/commit/c4994cfdecd115ac6d9f077a25adc36e02c94de0

You can test it out from here and let me know (feel free to reopen this if it still doesn't work): https://github.com/cjburkey01/ClaimChunk/suites/3109644685/artifacts/71151066
