### ISSUE TITLE
World Configs Missing Option to Disable Cross-Chunk Adjacent Block Placement

### ISSUE THREAD

**Issue by ghost** [cjburkey01/ClaimChunk#203]
**Versions**
Spigot Version: 1.17.1
ClaimChunk Version: 0.0.23-prev6

**Describe the bug**
Trying to place a chest next to another chest (making a double chest between claimed & unclaimed chunk) does not work

**To Reproduce**
1. Place one chest in a claimed chunk of yours
2. Try making a double chest between the claimed chunk & an unclaimed chunk

**Expected behavior**
it should make a double chest 

**Additional context**
-
![Schermafbeelding 2021-07-19 om 15 54 56 PM](https://user-images.githubusercontent.com/84584307/126171414-aaab8bee-21a1-4720-8f8f-2f70067a6ce3.png)

**Comment by cjburkey01** [comment]
This was implemented because a chest within a claim could be opened by someone in an unclaimed chunk simply by placing an adjacent chest. Now I thought I had a config option in the world profiles to handle it, but it seems like I forgot it. There will be a list of blocks that you can choose cannot be placed adjacent when on a chunk boundary.

**Comment by cjburkey01** [comment]
Note to self: Remember to add the list to the config!

**Comment by cjburkey01** [comment]
Finally added in https://github.com/cjburkey01/ClaimChunk/commit/ff1f631afd50e445fe9584065c98dbab94b3a626!
