### ISSUE TITLE
Downloading 0.0.22, getting 0.0.21

### ISSUE THREAD

**Issue by RisDN** [cjburkey01/ClaimChunk#221]
I'm downloading the latest release which is 0.0.22 but the plugin still launches in version 0.0.21.

**Comment by Geolykt** [comment]
That is a purely visual bug iirc. However it is highly recommended to use the latest development build instead due to the omnipresent issues with 0.0.22, currently that dev build is https://github.com/cjburkey01/ClaimChunk/suites/3962206135/artifacts/99547388

**Comment by cjburkey01** [comment]
Permissions are broken in the newer snapshots (don't know which one you suggested so ill recommend this one for the old permissions system) https://github.com/cjburkey01/ClaimChunk/suites/3818023030/artifacts/94442636

But like they said, it's a bug with 0.0.22 and I never got around to fixing it because 0.0.23 is this biggggg update
