### ISSUE TITLE
Outline claims with particles on command

### ISSUE THREAD

**Issue by JayemCeekay** [cjburkey01/ClaimChunk#75]
I was wondering if you would want to add a command that outlines all the current claims a player has with particles. The command could be like /chunk showclaims.

**Comment by EggLord54** [comment]
that could be quite intensive on the client if it showed the borders for each chunk as it currently does, as there could be many many particle effects taking place at the same time (for instance i have 200 chunks claimed in one area). something worth testing however...

**Comment by cjburkey01** [comment]
The current `/chunk show` command only outlines the current chunk because, as @EggLord54 said, it would be very intensive on the client and server. Spawning that many particles repeatedly would mean scheduling a ton of actions at once with Bukkit which probably wouldn't be a good idea.

There has recently been a Dynmap plugin developed so if you're interested in viewing claims across the world, I highly recommend it: https://www.spigotmc.org/resources/dynmap-claimchunk.71093/
