### ISSUE TITLE
Suggestion: Leaving chunk & exiting chunk should be colour coded

### ISSUE THREAD

**Issue by EggLord54** [cjburkey01/ClaimChunk#84]
**Is your feature request related to a problem? Please describe.**
When I leave chunks and enter chunks that are densely packed next to each other, I often find it quite difficult to make out whether I am entering or leaving someone else's chunk as it changes so quickly.

**Describe the solution you'd like**
I'd love some sort of easier way to distinguish this. maybe different colours for entering and exiting chunks. Maybe red for leaving chunks, and green for entering chunks? and something that's not as needed but would still be a much appreciated addition in my opinion, is the ability to change the colour of the entry text with your own rgb code! (say one player wants purple entrance text, the other wants pink) :)

**Describe alternatives you've considered**

**Additional context**

**Comment by cjburkey01** [comment]
Honestly all the messages should switch to Bukkit colors (like `&1`, `&2`, etc) instead of the current system which is three main colors: error, success, and info. The trouble is I think the title API won't do that automatically for me, so I'll have to build the text components manually when sending messages. I'll double check that this doesn't work though.

**Comment by cjburkey01** [comment]
All messages are now color-code-able with the new messages system (which moves messages from the `config.yml` into a `messages.json` file: https://github.com/cjburkey01/ClaimChunk/commit/0763273e984771a59de7fdb744b06c263db6a37e
