### ISSUE TITLE
Infinite money with 1st claim

### ISSUE THREAD

**Issue by PABessero** [cjburkey01/ClaimChunk#98]
**Versions**
Spigot Version: Paper 195
ClaimChunk Version: 0.0.15

**Describe the bug**
The 1st claim being unclaimed grants you money despite being free

**To Reproduce**
1. Claim your first chunk
2. Unclaim it
3. Profit

**Expected behavior**
The free claims being unclaimed shouldnt grant money back

**Comment by cjburkey01** [comment]
Are there any console errors? I had tested this recently and didn’t experience any issues.

**Comment by PABessero** [comment]
nope, it doesnt bring any issue it just refunds money despite none having been paid previously

**Comment by cjburkey01** [comment]
Fixed in https://github.com/cjburkey01/ClaimChunk/commit/fdc25e17179635faeb6ac749752f739cc3bdf3aa

Note: make sure your config is set to allow 1 free chunk if you still desire this behavior. The issue was that when set to 0, the plugin would still allow you to _claim_ 1 free chunk but it would still refund it as if it weren't free.
